Style fixes
gdgsrilanka/google-io-2024-web pull request #22
Opened 2024-06-29 15:15 UTC by donheshanthaka

This PR fixes the mobile first style issues on hero and speakers section. Also updated the navbar logo to svg

2024-06-29 16:33 UTC, chamodshehanka requested changes

2024-06-29 16:33 UTC, chamodshehanka commented on src/components/home/hero.tsx
> +//     <div>
remove these comments

2024-06-29 17:08 UTC, donheshanthaka commented
@chamodshehanka Sorry about the comments, I removed them

2024-06-30 01:22 UTC, chamodshehanka approved these changes

2024-06-30 01:22 UTC, merged